name: Maven Deploy

on:
  push:
    branches:
      release
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: ossrh 
        settings-path: ${{ github.workspace }} 

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Set up Maven Central Repository
      uses: actions/setup-java@v3
      with:
         java-version: '11'
         distribution: 'adopt'
         server-id: ossrh
         server-username: MAVEN_USERNAME
         server-password: MAVEN_PASSWORD
    - name: Publish package
      run: mvn --batch-mode deploy
      env:
         MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
         MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      

