name: Publish Maven Snapshot

on:
  workflow_dispatch:
  push:
    branches:
      - master  # Change this if needed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          server-id: ossrh  # Must match <server><id> in settings.xml
          server-username: OSS_USERNAME
          server-password: OSS_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Import GPG Key
        run: |
          echo "${{ secrets.GPG_SIGNING_KEY }}" | base64 --decode | gpg --batch --import
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          gpgconf --reload gpg-agent

      - name: Publish Snapshot to OSSRH
        run: mvn clean deploy -P release -DskipTests -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
        env:
          OSS_USERNAME: ${{ secrets.OSS_USERNAME }}
          OSS_PASSWORD: ${{ secrets.OSS_PASSWORD }}
          GPG_TTY: $(tty)  # Ensures GPG works in CI
