name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - release
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Install Java and Maven
      uses: actions/setup-java@v1
      with:
        java-version: 11
        cache: 'maven'
        server-id: ossrh
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: "-SNAPSHOT<"
        replace: "<"
        include: "pom.xml"
        regex: false
    - name: Release Maven package
      uses: samuelmeuli/action-maven-publish@v1.4.0
      with:
        gpg_private_key: ${{ secrets.GPG_SIGNING_KEY }}
        gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
        nexus_username: ${{ secrets.OSS_USERNAME }}
        nexus_password: ${{ secrets.OSS_PASSWORD }}
        maven_profiles: release
        maven_args: -P release
        maven_goals_phases: clean deploy -P release -DskipTests
