name: Maven Deploy

on:
  push:
    branches:
      - release
      - master
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: ossrh 
        settings-path: ${{ github.workspace }} 
        server-username: OSS_USERNAME # env variable for username in deploy
        server-password: OSS_PASSWORD # env variable for token in deploy
        gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }} # Value of the GPG private key to import
        gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }} # env variable for GPG private key passphrase

    - name: Import GPG Key
      uses: crazy-max/ghaction-import-gpg@v1
      env:
         GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
         PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Set up Maven Central Repository
      uses: actions/setup-java@v3
      with:
         java-version: '11'
         distribution: 'adopt'
         server-id: ossrh
         server-username: MAVEN_USERNAME
         server-password: MAVEN_PASSWORD
    - name: Publish package
      run: mvn --batch-mode deploy
      env:
         MAVEN_USERNAME: ${{ secrets.OSS_USERNAME }}
         MAVEN_PASSWORD: ${{ secrets.OSS_PASSWORD }}
      

